new action to push

diff --git a/actions/deploy_kubernetes/action.yaml b/actions/deploy_kubernetes/action.yaml
--- a/actions/deploy_kubernetes/action.yaml
+++ b/actions/deploy_kubernetes/action.yaml
@@ -96,44 +96,56 @@ runs:
     #     git add .
     #     git commit -am "deploy ${{ inputs.environment }} ${{ inputs.namespace }} ${{ inputs.name }} " || echo "Nothing to push"
 
-    # - name: Git push
-    #   uses: ad-m/github-push-action@master
-    #   with:
-    #     github_token: ${{ inputs.github_token }}
-    #     branch: main
-    #     force: true
-    #     directory: ./argocd
-    #     repository: nandoin/argocd
+    - name: GitHub Commit & Push
+      uses: actions-js/push@v1.4
+      with:
+        github_token: ${{ inputs.github_token }}
+        branch: main
+        #force: true
+        directory: ./argocd
+        repository: nandoin/argocd
+        author_name: "kustomize deploy"
+        author_email: "kustomize@deploy.com"
+        message: "deploy ${{ inputs.environment }} ${{ inputs.namespace }} ${{ inputs.name }}"
+
+    - name: Git push
+      uses: ad-m/github-push-action@master
+      with:
+        github_token: ${{ inputs.github_token }}
+        branch: main
+        force: true
+        directory: ./argocd
+        repository: nandoin/argocd
 
 
-    - name: Push Git Repo
-      shell: bash
-      env:
-        RETRIES: 3
-        COUNT: 0
-      working-directory: ./argocd
-      run: |
-        git config user.name action-deploy-${{ inputs.type }}
-        git config user.email action-deploy-${{ inputs.type }}@company.com
-        git add .
-        git status
-        git commit -m  "deploy ${{ inputs.environment }} ${{ inputs.namespace }} ${{ inputs.name }}" || echo "Nothing to push"
-        echo "git remote list"
-        git remote -v
-        echo "git remote remove"
-        git remote remove origin
-        echo "git remote add"
-        git remote add origin https://${{ inputs.github_token }}@github.com/nandoin/argocd.git
-        while [ $COUNT -lt $RETRIES ]; do
-          echo "Pushing ..."
-          set +e
-          git pull --rebase origin main && git push origin main; EC=$?
-          set -e
-          if [ $EC -eq 0 ]; then
-            RETRIES=0
-            break
-          fi
-          COUNT=$(($COUNT + 1))
-          sleep $((RANDOM % 10))
-          echo "Retrying $COUNT ..."
-        done   
+    # - name: Push Git Repo
+    #   shell: bash
+    #   env:
+    #     RETRIES: 3
+    #     COUNT: 0
+    #   working-directory: ./argocd
+    #   run: |
+    #     git config user.name action-deploy-${{ inputs.type }}
+    #     git config user.email action-deploy-${{ inputs.type }}@company.com
+    #     git add .
+    #     git status
+    #     git commit -m  "deploy ${{ inputs.environment }} ${{ inputs.namespace }} ${{ inputs.name }}" || echo "Nothing to push"
+    #     echo "git remote list"
+    #     git remote -v
+    #     echo "git remote remove"
+    #     git remote remove origin
+    #     echo "git remote add"
+    #     git remote add origin https://${{ inputs.github_token }}@github.com/nandoin/argocd.git
+    #     while [ $COUNT -lt $RETRIES ]; do
+    #       echo "Pushing ..."
+    #       set +e
+    #       git pull --rebase origin main && git push origin main; EC=$?
+    #       set -e
+    #       if [ $EC -eq 0 ]; then
+    #         RETRIES=0
+    #         break
+    #       fi
+    #       COUNT=$(($COUNT + 1))
+    #       sleep $((RANDOM % 10))
+    #       echo "Retrying $COUNT ..."
+    #     done   
